### ISSUE TITLE
XForm causes an NPE

### ISSUE THREAD

**Issue by adamretter** [betterFORM/betterFORM#10]
The following XForm can cause an NPE - 

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:bf="http://betterform.sourceforge.net/xforms">
    <head>
        <title>Security Groups</title>
    </head>
    <body>
        <xf:model>
            <xf:instance id="securitygroups" src="/exist/restxq/oecd/security/group"/>
            <xf:bind id="groups" nodeset="group"/>
        </xf:model>
        <div class="Section" dojotype="dijit.layout.ContentPane">
            <xf:group appearance="full" class="contactsFullGroup">
                <div class="Headline">Security Groups</div>
                <div class="description">List of currently defined Security Groups</div>
                <xf:group appearance="minimal">
                    <xf:repeat appearance="compact" bind="groups" class="orderListRepeat" id="repeatid">
                        <xf:group appearance="repeated">
                            <xf:output class="text-right" value="rootCote">
                                <xf:label class="contactsRepeatHeader">Root Cote</xf:label>
                            </xf:output>
                        </xf:group>
                    </xf:repeat>
                </xf:group>
            </xf:group>
        </div>
    </body>
</html>
```

The document from /exist/restxq/oecd/security/group looks like:

``` xml
<groups>
        <group>
            <rootCote>ADAM1</rootCote>
            <classification>Confidential</classification>
        </group>
    </groups>
```

This causes the following NPE and stack trace:

2013-01-17 14:07:55,575 [eXistThread-45] ERROR (XFormsFilter.java [doFilter]:217) - java.lang.NullPointerException 
de.betterform.xml.xforms.exception.XFormsException: java.lang.NullPointerException
    at de.betterform.xml.xforms.Container.dispatch(Container.java:461)
    at de.betterform.xml.xforms.Container.dispatch(Container.java:419)
    at de.betterform.xml.xforms.Container.initModels(Container.java:682)
    at de.betterform.xml.xforms.Container.init(Container.java:252)
    at de.betterform.xml.xforms.XFormsProcessorImpl.init(XFormsProcessorImpl.java:393)
    at de.betterform.agent.web.WebProcessor.init(WebProcessor.java:276)
    at de.betterform.agent.web.flux.FluxProcessor.init(FluxProcessor.java:68)
    at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:209)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:365)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NullPointerException
    at de.betterform.xml.xforms.ui.RepeatItem.getLocationPath(RepeatItem.java:90)
    at de.betterform.xml.xforms.ui.BindingElement.getInstanceId(BindingElement.java:325)
    at de.betterform.xml.xforms.ui.state.UIElementStateUtil.getModelItem(UIElementStateUtil.java:112)
    at de.betterform.xml.xforms.ui.state.BoundElementState.init(BoundElementState.java:80)
    at de.betterform.xml.xforms.ui.BindingElement.initializeElementState(BindingElement.java:467)
    at de.betterform.xml.xforms.ui.RepeatItem.init(RepeatItem.java:205)
    at de.betterform.xml.xforms.Initializer.initXFormsObject(Initializer.java:270)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:220)
    at de.betterform.xml.xforms.ui.RepeatItem.init(RepeatItem.java:206)
    at de.betterform.xml.xforms.ui.Repeat.initializeRepeatItem(Repeat.java:646)
    at de.betterform.xml.xforms.ui.Repeat.initializeRepeat(Repeat.java:393)
    at de.betterform.xml.xforms.ui.Repeat.init(Repeat.java:277)
    at de.betterform.xml.xforms.Initializer.initXFormsObject(Initializer.java:270)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:220)
    at de.betterform.xml.xforms.ui.AbstractUIElement.initializeChildren(AbstractUIElement.java:167)
    at de.betterform.xml.xforms.ui.BindingElement.init(BindingElement.java:95)
    at de.betterform.xml.xforms.ui.Group.init(Group.java:60)
    at de.betterform.xml.xforms.Initializer.initXFormsObject(Initializer.java:270)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:220)
    at de.betterform.xml.xforms.ui.AbstractUIElement.initializeChildren(AbstractUIElement.java:167)
    at de.betterform.xml.xforms.ui.BindingElement.init(BindingElement.java:95)
    at de.betterform.xml.xforms.ui.Group.init(Group.java:60)
    at de.betterform.xml.xforms.Initializer.initXFormsObject(Initializer.java:270)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:220)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:258)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:258)
    at de.betterform.xml.xforms.Initializer.initializeUIElements(Initializer.java:186)
    at de.betterform.xml.xforms.model.Model.modelConstructDone(Model.java:884)
    at de.betterform.xml.xforms.model.Model.performDefault(Model.java:709)
    at de.betterform.xml.events.impl.DefaultXMLEventService.dispatch(DefaultXMLEventService.java:196)
    at de.betterform.xml.xforms.Container.dispatch(Container.java:441)
    ... 31 more

**Comment by JoernT** [comment]
looks like the empty namespace is missing. Try adding xmlns="" to the instance element or on the the root element of the data.

**Comment by windauer** [comment]
Can this ticket be closed? Did Joern Tipp workout?
